### ISSUE TITLE
Error: game part creation failed!

### ISSUE THREAD

**Issue by RivelinoDomingo** [arcadenea/iso2opl#2]
desktop:~/iso2opl$ ./iso2opl ~/Downloads/PS2/stf/stf_alfa.iso /dev/sdc1 "teste" DVD
Error: game part creation failed!

Do you know if this method still works in 2020?

**Comment by arcadenea** [comment]
Seems like iso2opl cannot write in the destination path that you point. Does it exist? Is it writable?

**Comment by RivelinoDomingo** [comment]
yes, I was pointing to the USB stick that I use on the PS2.  and my user has read and write permission, but I can try pointing to a folder on my hard drive.

**Comment by RivelinoDomingo** [comment]
As you said before ... it was probably the problem you mentioned. using a folder from my HD it worked perfectly !!! I don't know why indicating the location of my flash drive gave the error "/ dev / sdc1" I will find out.
Thank you so much for your software and your answer!


![Screenshot_20200406_013323](https://user-images.githubusercontent.com/27700770/78523310-ab462980-77a6-11ea-9333-4c060afeb454.png)

**Comment by arcadenea** [comment]
Try /dev/sdc, i don't remember why but i always used the device location, not the partition. Oh and it's not MY software, i just pulled the original repo to improve the makefile. But thanks anyway!
