### ISSUE TITLE
Correct command syntax in README

### ISSUE THREAD

**Issue by templalizer1284-zz** [arcadenea/iso2opl#3]
Instead of putting device file like /dev/sdb or /dev/sdc it should be mounted path like /mnt/flash or /mnt/cd1/.

**Comment by allanvobraun** [comment]
'/dev/sdb' doesn't work?

**Comment by allanvobraun** [comment]
Yeah i just tested it and doesn't really work. But  using "/media/user/devicelabel" worked for me. I think I'll do a pull request updating the readme.

**Comment by arcadenea** [comment]
You are correct, it's the mounted path of the device. I've updated the readme.

Thanks!
